export const basic = {
  borderWidth: 0,
  borderStyle: 'solid',
  borderRadius: '0.25em',
  display: 'inline-flex',
  fontSize: '1rem',
  lineHeight: '1.5rem',
  letterSpacing: '0.015rem',
  padding: '.65rem 1rem',
  paddingLeft: '2.5rem',
  paddingRight: '2.5rem',
  verticalAlign: 'middle',
  transition: 'top 1s',
  textAlign: 'center',
}

export const raised = {
  borderWidth: 0,
  borderStyle: 'solid',
  borderRadius: '0.25em',
  display: 'inline-flex',
  fontSize: '1rem',
  lineHeight: '1.5rem',
  letterSpacing: '0.015rem',
  padding: '.65rem 1rem',
  paddingLeft: '2.5rem',
  paddingRight: '2.5rem',
  verticalAlign: 'middle',
  transition: 'top 1s',
  textAlign: 'center',
}
